### ISSUE TITLE
Adding example of how reverse a dictionary

### ISSUE THREAD

**Issue by dianedelallee** [PythonistaCafe/reading-code#2]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to reverse the key-value of a dictionary

**Describe the solution you'd like**
I would like to put 
`inv_dict = {value: key for key, value in traditional_dict.items()}`
in `dictionaries/main.py`

**Describe alternatives you've considered**
None for the moment, but happy to discuss

**Comment by rileyjohngibbs** [comment]
You might also consider using the `bidict` package, which protects against the possibility of two keys having the same value.
