### ISSUE TITLE
Clarify the dictionary inversion example

### ISSUE THREAD

**Issue by rileyjohngibbs** [PythonistaCafe/reading-code#4]
**Is your feature request related to a problem? Please describe.**
The example of an inverted dictionary is misleading.

**Describe the solution you'd like**
I'd like to clarify that a dictionary is not guaranteed to have a true inverse.

**Describe alternatives you've considered**
I thought about replacing the example with `bidict`, but the file in question seems to be intended only for standard lib examples.

**Additional context**
Example of a dictionary that has no inverse:
```python
d = {'a': 'v', 'b': 'v'}
d_ = {v: k for k, v in d.items()}
print(d_)  # {'v': 'b'}
```

**Comment by dianedelallee** [comment]
As you say the main file is for the standard lib.
But we can create a file or folder for example with non-standard lib.
It quite interesting to discover new lib.

Thanks for `bidict`, I will definitively use it.
